
DISPLAY_SCALE = 4
INITIAL_BALL_SPEED =  DISPLAY_SCALE/2
INITIAL_PLYR_SPEED = 1 * DISPLAY_SCALE
GAME_FPS = 60
DISPLAY_SIZE = GAME_WIDTH, GAME_HEIGHT = 160 * DISPLAY_SCALE, 192 * DISPLAY_SCALE
COLLISION_TOL =  1+DISPLAY_SCALE /2
STARTING_LIVES = 1