WIDTH = 800
HEIGHT = 600

PADDLE_LENGTH = 600
PADDLE_WIDTH = 10
PADDLE_SPACING = 100


PADDLE_1_Y1 = HEIGHT - PADDLE_SPACING
MARIO_Y1 = PADDLE_1_Y1 - 30
PADDLE_1_COORDS = (0, PADDLE_1_Y1, WIDTH, PADDLE_WIDTH)

PADDLE_2_Y1 = PADDLE_1_Y1 - PADDLE_SPACING
PADDLE_2_COORDS = (WIDTH - PADDLE_LENGTH, PADDLE_2_Y1, WIDTH,  PADDLE_WIDTH)

PADDLE_3_Y1 = PADDLE_2_Y1 - PADDLE_SPACING
PADDLE_3_COORDS = (0, PADDLE_3_Y1, PADDLE_LENGTH,  PADDLE_WIDTH)

PADDLE_4_Y1 = PADDLE_3_Y1 - PADDLE_SPACING
PADDLE_4_COORDS = (WIDTH - PADDLE_LENGTH, PADDLE_4_Y1,  PADDLE_LENGTH,  PADDLE_WIDTH)

PADDLE_5_Y1 = PADDLE_4_Y1 - PADDLE_SPACING
PADDLE_5_COORDS = (0, PADDLE_5_Y1, PADDLE_LENGTH,  PADDLE_WIDTH)



STAIR_1_COORDS = 600, PADDLE_2_Y1+PADDLE_WIDTH, 50, PADDLE_SPACING - PADDLE_WIDTH
STAIR_2_COORDS = 400, PADDLE_3_Y1+PADDLE_WIDTH, 50, PADDLE_SPACING - PADDLE_WIDTH
STAIR_3_COORDS = 250, PADDLE_4_Y1+PADDLE_WIDTH, 50, PADDLE_SPACING - PADDLE_WIDTH
STAIR_4_COORDS = 500, PADDLE_5_Y1+PADDLE_WIDTH, 50, PADDLE_SPACING - PADDLE_WIDTH