create_canton(conn, 'Liberia', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Nicoya', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Santa Cruz', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Bagaces', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Carrillo', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Cañas', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Abangares', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Tilarán', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Nandayure', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'La Cruz', 'Guanacaste', 'Costa Rica')
create_canton(conn, 'Hojancha', 'Guanacaste', 'Costa Rica')

create_distrito(conn, 'Liberia','Liberia', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Cañas Dulces','Liberia', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Mayorga','Liberia', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Nacascolo','Liberia', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Curubandé','Liberia', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Nicoya','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Mansión','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'San Antonio','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Quebrada Honda','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Sámara','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Nosara','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Belén de Nosarita','Nicoya', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Santa Cruz','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Bolsón','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Veintisiete de Abril','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Tempate','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Cartagena','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Cuajiniquil','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Diriá','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Cabo Velas','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Tamarindo','Santa Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Bagaces','Bagaces', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'La Fortuna','Bagaces', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Mogote','Bagaces', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Río Naranjo','Bagaces', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Filadelfia','Carrillo', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Palmira','Carrillo', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Sardinal','Carrillo', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Belén','Carrillo', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Cañas','Cañas', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Palmira','Cañas', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'San Miguel','Cañas', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Bebedero','Cañas', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Porozal','Cañas', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Las Juntas','Abangares', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Sierra','Abangares', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'San Juan','Abangares', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Colorado','Abangares', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Tilarán','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Quebrada Grande','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Tronadora','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Santa Rosa','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Líbano','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Tierras Morenas','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Arenal','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Cabeceras','Tilarán', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Carmona','Nandayure', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Santa Rita','Nandayure', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Zapotal','Nandayure', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'San Pablo','Nandayure', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Porvenir','Nandayure', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Bejuco','Nandayure', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'La Cruz','La Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Santa Cecilia','La Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'La Garita','La Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Santa Elena','La Cruz', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Hojancha','Hojancha', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Monte Romo','Hojancha', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Puerto Carrillo','Hojancha', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Huacas','Hojancha', 'Guanacaste', 'Costa Rica')
create_distrito(conn, 'Matambú','Hojancha', 'Guanacaste', 'Costa Rica')
