create_canton(conn, 'Limón', 'Limón', 'Costa Rica')
create_canton(conn, 'Pococí', 'Limón', 'Costa Rica')
create_canton(conn, 'Siquirres', 'Limón', 'Costa Rica')
create_canton(conn, 'Talamanca', 'Limón', 'Costa Rica')
create_canton(conn, 'Matina', 'Limón', 'Costa Rica')
create_canton(conn, 'Guácimo', 'Limón', 'Costa Rica')

create_distrito(conn,'Limón','Limón', 'Limón', 'Costa Rica')
create_distrito(conn,'Valle La Estrella','Limón', 'Limón', 'Costa Rica')
create_distrito(conn,'Río Blanco','Limón', 'Limón', 'Costa Rica')
create_distrito(conn,'Matama','Limón', 'Limón', 'Costa Rica')
create_distrito(conn,'Guápiles','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'Jiménez','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'La Rita','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'Roxana','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'Cariari','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'Colorado','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'La Colonia','Pococí', 'Limón', 'Costa Rica')
create_distrito(conn,'Siquirres','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'Pacuarito','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'Florida','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'Germania','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'El Cairo','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'Alegría','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'Reventazón','Siquirres', 'Limón', 'Costa Rica')
create_distrito(conn,'Bratsi','Talamanca', 'Limón', 'Costa Rica')
create_distrito(conn,'Sixaola','Talamanca', 'Limón', 'Costa Rica')
create_distrito(conn,'Cahuita','Talamanca', 'Limón', 'Costa Rica')
create_distrito(conn,'Telire','Talamanca', 'Limón', 'Costa Rica')
create_distrito(conn,'Matina','Matina', 'Limón', 'Costa Rica')
create_distrito(conn,'Batán','Matina', 'Limón', 'Costa Rica')
create_distrito(conn,'Carrandi','Matina', 'Limón', 'Costa Rica')
create_distrito(conn,'Guácimo','Guácimo', 'Limón', 'Costa Rica')
create_distrito(conn,'Mercedes','Guácimo', 'Limón', 'Costa Rica')
create_distrito(conn,'Pocora','Guácimo', 'Limón', 'Costa Rica')
create_distrito(conn,'Río Jiménez','Guácimo', 'Limón', 'Costa Rica')
create_distrito(conn,'Duacarí','Guácimo', 'Limón', 'Costa Rica')
